### PR TITLE
fix: remove unused import that causes NoClassDefFoundError

### LINKED ISSUE #222: [2.1.20] Crash clicking on a frame when WaterVision is missing
I'm unable to open the player GUI after updating to v2.1.20 on fabric 1.21.1.

**Steps to reproduce:**
– Put a frame in your world.
– Right click to open the GUI.
– Experience the crash instead.

**Logs:**
latest.log: https://mclo.gs/fRLbgzf
crash report: https://mclo.gs/kbWujBr

### PR DESCRIPTION
**Pull request by SNWCreations**
This appends to #222 because that fix is incomplete, the direct reference towards WaterVision mod classes were removed but the import is not removed, and the unused import remained in compiled bytecode so the client will still crash, making the fix totally invalid.
Tested in production environment and it worked well.

amend of https://github.com/SrRapero720/waterframes/commit/96c798c2e6ea3a7bb2609f538f66cdc66bf4ba6d
should fully closes #222
also relates to https://github.com/CreativeMD/CreativeCore/issues/290

### CODE REVIEW

**Comment by SrRapero720** [comment]
the import has nothing related, compiler automatically removes those unused, on the other hand, the 1.20.1 version with that patch has not been released yet.

But thanks to you, i notice that the check to open the screen is also wrong, because it checks that "if watervision is installed then do nothing", I need to look at that
