### ISSUE TITLE
[Crash] when right clicking TV with creativecore 2.12.32

### ISSUE THREAD

**Issue by MindStudioOfficial** [SrRapero720/WATERFrAMES#162]
Server (MP) / Client (SP) crashes when right clicking a TV after updating creative core to 2.12.32.

Downgrading to 2.12.23 of creativecore solves the problem.

[crash-2025-02-13_00.16.05-server.txt](https://github.com/user-attachments/files/18775724/crash-2025-02-13_00.16.05-server.txt)

```
java.lang.NoSuchMethodError: 'void me.srrapero720.waterframes.common.screens.widgets.WidgetURLTextField.setMaxStringLength(int)'
	at knot//me.srrapero720.waterframes.common.screens.widgets.WidgetURLTextField.<init>(WidgetURLTextField.java:22)
	at knot//me.srrapero720.waterframes.common.screens.DisplayScreen.<init>(DisplayScreen.java:104)
	at knot//me.srrapero720.waterframes.common.block.DisplayBlock.create(DisplayBlock.java:75)
	at knot//team.creative.creativecore.common.gui.creator.GuiCreator$GuiCreatorBlock.lambda$new$0(GuiCreator.java:107)
	at knot//team.creative.creativecore.common.gui.packet.OpenGuiPacket.openGuiOnServer(OpenGuiPacket.java:38)
	at knot//team.creative.creativecore.common.gui.creator.GuiCreator.openGui(GuiCreator.java:52)
	at knot//team.creative.creativecore.common.gui.creator.GuiCreator$GuiCreatorBlock.open(GuiCreator.java:120)
	at knot//team.creative.creativecore.common.gui.creator.GuiCreator$GuiCreatorBlock.open(GuiCreator.java:113)
	at knot//me.srrapero720.waterframes.common.block.DisplayBlock.method_55765(DisplayBlock.java:110)
	at knot//net.minecraft.class_4970$class_4971.method_55780(class_4970.java:1169)
	at knot//net.minecraft.class_3225.method_14262(class_3225.java:348)
	at knot//net.minecraft.class_3244.method_12046(class_3244.java:1158)
	at knot//net.minecraft.class_2885.method_12547(class_2885.java:42)
	at knot//net.minecraft.class_2885.method_11054(class_2885.java:10)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_3738.run(class_3738.java:18)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864)
	at knot//net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846)
	at knot//net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:121)
	at knot//net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Fabric 1.21.1 (see crash log for details)

**Comment by JustOneMorePaul** [comment]
Seconding this issue and the fix. seems an update to creative core removed a method or renamed it?

**Comment by SrRapero720** [comment]
fixed
